version : '3'

networks:
    dompp:
        driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9000:8000"
      - "9001:8001"
      - "9002:8002"
    volumes:
      - ./htdocs:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dompp

  php:
    build:
      context: .
      dockerfile: ./php/php.dockerfile
    container_name: php
    volumes:
      - ./htdocs:/var/www/
    networks:
      - dompp
    
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    ports:
    - 3306:3306
    networks:
      - dompp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    volumes:
      - ./phpmyadmin:/var/lib/mysql
    ports:
      - 8183:80
    networks:
      - dompp