version : '3'

networks:
    dompp:
        driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./htdocs/${PROJECT_DIR}:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dompp
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: ./php/${PHP_DOCKERFILE}
    container_name: php
    volumes:
      - ./htdocs/${PROJECT_DIR}:/var/www/
    networks:
      - dompp
    
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    ports:
    - ${MYSQL_PORT}:3306
    networks:
      - dompp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    volumes:
      - ./phpmyadmin:/var/lib/mysql
    ports:
      - ${PMA_PORT}:80
    networks:
      - dompp